In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split as tts

In [2]:
X = pd.read_csv('example_data.zip')
y = X.pop('target')
X

,Experimental,age,0,1,2,3,4,5,6,7,...,39,40,41,42,43,44,45,46,47,48
0,False,46,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,...,0.000698,-0.002430,-0.001436,-0.000747,0.001543,0.002786,-0.000724,0.000757,-0.000242,-0.000883
1,False,52,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,...,-0.000952,-0.000163,-0.001199,0.002260,-0.002863,0.004478,0.000851,0.001854,0.001907,-0.002350
2,True,35,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-0.002058,0.000095,0.001030,-0.004264,-0.001414,0.000441,-0.000028,-0.000506,-0.000038,0.000065
3,False,39,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.000905,-0.000319,-0.000555,-0.000819,-0.000906,0.001184,-0.000844,0.002494,0.000275,-0.000603
4,True,33,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,...,-0.000993,0.000620,0.001139,-0.002792,0.001248,-0.002302,-0.000117,0.002084,0.000879,-0.001569
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,False,45,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,0.002344,0.000715,-0.000150,0.000210,0.001329,0.001474,-0.000848,-0.001374,-0.000155,0.000271
99996,False,30,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,-0.001740,-0.001936,0.000320,-0.001136,-0.002074,0.002167,0.001766,-0.000187,-0.001322,0.002169
99997,False,40,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,...,-0.001834,-0.000517,0.000121,0.000679,-0.002143,-0.001451,0.000462,0.002434,0.000163,-0.001323
99998,False,33,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,...,-0.003067,0.000104,-0.000033,0.001236,0.001524,-0.001263,-0.000690,0.000230,0.000409,0.004947
99999,False,45,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.000333,0.001528,0.002478,0.003144,-0.001893,0.000646,-0.000206,0.001547,-0.002127,0.000117

In [3]:
X_train, X_test, y_train, y_test = tts(X,
                                       y,
                                       stratify=X['Experimental'])